[package]
name = "meerkat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
meerkat-protocol = { path = "../shared" }
anyhow = "1"
futures = "0.3"
libp2p = { version = "0.56", features = ["tokio", "tcp", "noise", "yamux"] }
libp2p-stream = "0.4.0-alpha"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1"
